export const ACTIVITY_TYPES = {
  // Property Activities
  PROPERTY_CREATED: "PROPERTY_CREATED",
  PROPERTY_EDITED: "PROPERTY_EDITED",
  PROPERTY_DELETED: "PROPERTY_DELETED",
  PROPERTY_SAVED: "PROPERTY_SAVED",
  PROPERTY_UNSAVED: "PROPERTY_UNSAVED",

  // Contact Activities
  CONTACT_REVEALED: "CONTACT_REVEALED",
  CONTACT_VIEWED: "CONTACT_VIEWED",

  // Messaging
  MESSAGE_SENT: "MESSAGE_SENT",

  // Payment Activities
  PAYMENT_MADE: "PAYMENT_MADE",
  PAYMENT_COMPLETED: "PAYMENT_COMPLETED",

  // Listing Activities
  LISTING_PROMOTED: "LISTING_PROMOTED",

  // Profile Activities
  PROFILE_UPDATED: "PROFILE_UPDATED",
  EMAIL_VERIFIED: "EMAIL_VERIFIED",

  // Authentication
  LOGIN: "LOGIN",
  LOGOUT: "LOGOUT",
  PASSWORD_RESET:"PASSWORD_RESET"
};