export const C = {
  cream: "#FAFAF7",
  white: "#FFFFFF",

  ink: "#141414",
  inkMuted: "#6B6B6B",
  inkLight: "#9A9A9A",

  gold: "#C8A96E",
  goldLight: "#F5EDD8",

  border: "#E8E8E3",

  green: "#2D6A4F",
  greenBg: "#EAF4EE",

  red: "#C0392B",
  redBg: "#FDECEA",

  blue: "#4361EE",
  blueBg: "#EEF2FF",
  dark: "#141414",
  sidebar: "#141414",
  cardShadow: "0 2px 16px rgba(0,0,0,0.06)",
  cardHover: "0 12px 40px rgba(0,0,0,0.13)",
};

export const stats    = [{ value: "12K+", label: "Properties Listed" }, { value: "8K+", label: "Happy Tenants" }, { value: "320+", label: "Cities Covered" }, { value: "98%", label: "Satisfaction Rate" }];  

export const properties = [
  { id: 1, title: "Skyline Penthouse", location: "Bandra West, Mumbai", price: "₹4,20,000/mo", type: "Rent", beds: 3, baths: 2, sqft: "2,100", tag: "Featured", img: "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?w=600&q=80" },
  { id: 2, title: "Garden Villa", location: "Koregaon Park, Pune", price: "₹1.8 Cr", type: "Buy", beds: 4, baths: 3, sqft: "3,400", tag: "New", img: "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?w=600&q=80" },
  { id: 3, title: "Studio Loft", location: "Indiranagar, Bangalore", price: "₹28,000/mo", type: "Rent", beds: 1, baths: 1, sqft: "680", tag: "Popular", img: "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?w=600&q=80" },
  { id: 4, title: "Heritage Bungalow", location: "Jubilee Hills, Hyderabad", price: "₹3.2 Cr", type: "Buy", beds: 5, baths: 4, sqft: "4,800", tag: "Luxury", img: "https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=600&q=80" },
  { id: 5, title: "Modern Flat", location: "Salt Lake, Kolkata", price: "₹18,000/mo", type: "Rent", beds: 2, baths: 2, sqft: "1,050", tag: null, img: "https://images.unsplash.com/photo-1493809842364-78817add7ffb?w=600&q=80" },
  { id: 6, title: "Riverside Apartment", location: "Navrangpura, Ahmedabad", price: "₹95 L", type: "Buy", beds: 2, baths: 1, sqft: "1,200", tag: "Hot Deal", img: "https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=600&q=80" },
];


export const categories = [{ icon: "🏢", label: "Apartments" }, { icon: "🏠", label: "Villas" }, { icon: "🏗️", label: "Under Construction" }, { icon: "🏡", label: "Bungalows" }, { icon: "🛖", label: "Studios" }, { icon: "🏬", label: "Commercial" }];
export const steps    = [{ n: "01", title: "Search Properties", desc: "Browse thousands of verified listings by city, locality, budget, or property type." }, { n: "02", title: "Schedule a Visit", desc: "Book instant site visits with verified agents or directly with owners." }, { n: "03", title: "Verify & Negotiate", desc: "Review documents, negotiate the price, and get full transparency at every step." }, { n: "04", title: "Move In", desc: "Sign digitally, pay securely, and get the keys. That simple." }];
export const footerCols = [{ title: "Company", links: ["About Us", "Careers", "Blog"] }, { title: "Explore", links: ["Buy", "Rent", "Sell", "Commercial", "Premium"] }, { title: "Support", links: ["Help Center", "Contact Us", "Privacy Policy", "developer"] }];

 
export const propertyTypes = ["All", "Apartment", "Villa", "Bungalow"];
export const budgetRanges = [
  { label: "Any", min: 0, max: Infinity },
  { label: "< ₹50L", min: 0, max: 5000000 },
  { label: "₹50L–1Cr", min: 5000000, max: 10000000 },
  { label: "₹1–3 Cr", min: 10000000, max: 30000000 },
  { label: "₹3 Cr+", min: 30000000, max: Infinity },
];
export const bedsOptions = ["Any", "1", "2", "3", "4+"];
export const sortOptions = ["Relevance", "Price: Low–High", "Price: High–Low", "Newest", "Most Popular"];

 
export const POPULAR_LOCATIONS = [
  "Mumbai",
  "Delhi",
  "Bengaluru",
  "Hyderabad",
  "Pune",
  "Chennai",
  "Kolkata",
  "Ahmedabad",
  "Surat",
  "Jaipur",
  "Lucknow",
  "Kanpur",
  "Nagpur",
  "Indore",
  "Thane",
  "Bhopal",
  "Visakhapatnam",
  "Pimpri-Chinchwad",
  "Patna",
  "Vadodara",
  "Ghaziabad",
  "Ludhiana",
  "Agra",
  "Nashik",
  "Faridabad",
  "Meerut",
  "Rajkot",
  "Kalyan",
  "Vasai",
  "Varanasi",
  "Srinagar",
  "Aurangabad",
  "Dhanbad",
  "Amritsar",
  "Navi Mumbai",
  "Allahabad",
  "Ranchi",
  "Howrah",
  "Coimbatore",
  "Jabalpur",
  "Gwalior",
  "Vijayawada",
  "Jodhpur",
  "Madurai",
  "Raipur",
  "Kota",
  "Guwahati",
  "Chandigarh",
  "Solapur",
  "Hubli",
  "Tiruchirappalli",
  "Bareilly",
  "Mysuru",
  "Tiruppur",
  "Gurgaon",
  "Aligarh",
  "Jalandhar",
  "Bhubaneswar",
  "Salem",
  "Warangal",
  "Mira Bhayandar",
  "Thiruvananthapuram",
  "Bhiwandi",
  "Saharanpur",
  "Guntur",
  "Amravati",
  "Bikaner",
  "Noida",
  "Jamshedpur",
  "Bhilai",
  "Cuttack",
  "Firozabad",
  "Kochi",
  "Nellore",
  "Bhavnagar",
  "Dehradun",
  "Durgapur",
  "Asansol",
  "Rourkela",
  "Nanded",
  "Kolhapur",
  "Ajmer",
  "Akola",
  "Gulbarga",
  "Jamnagar",
  "Ujjain",
  "Loni",
  "Siliguri",
  "Jhansi",
  "Ulhasnagar",
  "Jammu",
  "Sangli",
  "Mangalore",
  "Erode",
  "Belgaum",
  "Kurnool",
  "Ambattur",
  "Rajahmundry",
  "Tirunelveli",
  "Malegaon",
  "Gaya",
  "Jalgaon",
  "Udaipur",
  "Maheshtala",
  "Davanagere",
  "Kozhikode",
  "Kurnool",
  "Rajpur Sonarpur",
  "Bokaro",
  "South Dumdum",
  "Bellary",
  "Patiala",
  "Gopalpur",
  "Agartala",
  "Bhagalpur",
  "Muzaffarnagar",
  "Bhatpara",
  "Panihati",
  "Latur",
  "Dhule",
  "Rohtak",
  "Korba",
  "Bhilwara",
  "Berhampur",
  "Muzaffarpur",
  "Ahmednagar",
  "Mathura",
  "Kollam",
  "Avadi",
  "Kadapa",
  "Kamarhati",
  "Bilaspur",
  "Shahjahanpur",
  "Satara",
  "Bijapur",
  "Rampur",
  "Shivamogga",
  "Chandrapur",
  "Junagadh",
  "Thrissur",
  "Alwar",
  "Bardhaman",
  "Kulti",
  "Kakinada",
  "Nizamabad",
  "Parbhani",
  "Tumkur",
  "Hisar",
  "Ozhukarai",
  "Bihar Sharif",
  "Panipat",
  "Darbhanga",
  "Bally",
  "Aizawl",
  "Dewas",
  "Ichalkaranji",
  "Karnal",
  "Bathinda",
  "Jalna",
  "Eluru",
  "Barasat",
  "Kirari Suleman Nagar",
  "Purnia",
  "Satna",
  "Mau",
  "Sonipat",
  "Farrukhabad",
  "Sagar",
  "Rourkela",
  "Durg",
  "Imphal",
  "Ratlam",
  "Hapur",
  "Arrah",
  "Karimnagar",
  "Anantapur",
  "Etawah",
  "Ambarnath",
  "North Dumdum",
  "Bharatpur",
  "Begusarai",
  "New Delhi",
  "Gandhidham",
  "Baranagar",
  "Tiruvottiyur",
  "Puducherry",
  "Sikar",
  "Thoothukudi",
  "Rewa",
  "Mirzapur",
  "Raichur",
  "Pali",
  "Ramagundam",
  "Haridwar",
  "Vijayanagaram",
  "Katihar",
  "Nagercoil",
  "Sri Ganganagar",
  "Karawal Nagar",
  "Mango",
  "Thanjavur",
  "Bulandshahr",
  "Uluberia",
  "Murwara",
  "Sambhal",
  "Singrauli",
  "Nadiad",
  "Secunderabad",
  "Naihati",
  "Yamunanagar",
  "Bidhan Nagar",
  "Pallavaram",
  "Bidar",
  "Munger",
  "Panchkula",
  "Burhanpur",
  "Raurkela",
  "Kharagpur",
  "Dindigul",
  "Gandhinagar",
  "Hospet",
  "Nangloi Jat",
  "Malda",
  "Ongole",
  "Deoghar",
  "Chapra",
  "Haldia",
  "Khandwa",
  "Morena",
  "Amroha",
  "Anand",
  "Bhind",
  "Bhalswa Jahangir Pur",
  "Madhyamgram",
  "Bhiwani",
  "Navi Mumbai",
  "Baharampur",
  "Ambala",
  "Morbi",
  "Fatehpur",
  "Raebareli",
  "Khora",
  "Chittoor",
  "Bhusawal",
  "Orai",
  "Bahraich",
  "Phusro",
  "Vellore",
  "Mehsana",
  "Raiganj",
  "Sirsa",
  "Danapur",
  "Serampore",
  "Sultan Pur Majra",
  "Guna",
  "Jaunpur",
  "Panvel",
  "Shivpuri",
  "Surendranagar",
  "Unnao",
  "Chinsurah",
  "Alappuzha",
  "Kottayam",
  "Machilipatnam",
  "Shimla",
  "Adoni",
  "Tenali",
  "Proddatur",
  "Saharsa",
  "Hindupur",
  "Sasaram",
  "Hajipur",
  "Bhimavaram",
  "Kumbakonam",
  "Dehri",
  "Madanapalle",
  "Siwan",
  "Bettiah",
  "Guntakal",
  "Srikakulam",
  "Motihari",
  "Dharmavaram",
  "Gudivada",
  "Narasaraopet",
  "Bagalkot",
  "Miryalaguda",
  "Tadipatri",
  "Kishanganj",
  "Karaikudi",
  "Suryapet",
  "Jorhat",
  "Pathankot",
  "Hoshiarpur",
  "Batala",
  "Barnala",
  "Moga",
  "Abohar",
  "Khanna",
  "Phagwara",
  "Muktsar",
  "Faridkot",
  "Gobindgarh",
  "Tinsukia",
  "Tezpur",
  "Nagaon",
  "Silchar",
  "Dimapur",
  "Kohima",
  "Shillong",
  "Itanagar",
  "Gangtok",
  "Leh",
  "Kargil",
  "Port Blair",
  "Daman",
  "Silvassa",
  "Kavaratti",
  "Buxar",
  "Jehanabad",
  "Samastipur",
  "Lakhisarai",
  "Araria",
  "Madhepura",
  "Jamui",
  "Nawada",
  "Sheikhpura",
  "Bongaigaon",
  "Goalpara",
  "Karimganj",
  "Diphu",
  "Haflong",
  "Pasighat",
  "Roing",
  "Tawang",
  "Ziro",
  "Bomdila",
  "Naharlagun",
  "Churachandpur",
  "Thoubal",
  "Ukhrul",
  "Senapati",
  "Lunglei",
  "Champhai",
  "Saiha",
  "Kolasib",
  "Mokokchung",
  "Tuensang",
  "Wokha",
  "Mon",
  "Phek",
  "Zunheboto",
  "Peren",
  "Namchi",
  "Mangan",
  "Ravangla",
  "Jowai",
  "Tura",
  "Williamnagar",
  "Nongstoin",
  "Bishnupur",
  "Kailashahar",
  "Udaipur Tripura",
  "Belonia",
  "Dharmanagar",
  "Ambikapur",
  "Jagdalpur",
  "Dhamtari",
  "Mahasamund",
  "Kanker",
  "Raigarh",
  "Koraput",
  "Balasore",
  "Sambalpur",
  "Jharsuguda",
  "Baripada",
  "Puri",
  "Balangir",
  "Keonjhar",
  "Bhadrak",
  "Angul",
  "Jeypore",
  "Rayagada",
  "Paradip",
  "Kendrapara",
  "Bargarh",
  "Sundargarh",
  "Bhawanipatna",
  "Nayagarh",
  "Phulbani"
];

export const AMENITIES_LIST = [
  { id: "Gym", label: "Gym", icon: "🏋️" },
  { id: "Swimming Pool", label: "Swimming Pool", icon: "🏊" },
  { id: "Security", label: "24/7 Security", icon: "🔒" },
  { id: "Lift", label: "Lift / Elevator", icon: "🛗" },
  { id: "Park", label: "Park / Garden", icon: "🌳" },
  { id: "Clubhouse", label: "Clubhouse", icon: "🏛️" },
  { id: "Power Backup", label: "Power Backup", icon: "⚡" },
  { id: "Play Area", label: "Play Area", icon: "🎪" },
  { id: "Parking", label: "Parking", icon: "🚗" },
  { id: "Air Conditioning", label: "Air Conditioning", icon: "❄️" },
  { id: "Wi-Fi", label: "Wi-Fi", icon: "📶" },
  { id: "Laundry", label: "Laundry", icon: "🧺" },
];

export const PROPERTY_TYPES = ["Apartment", "Villa", "Bungalow", "Studio", "Penthouse", "Commercial", "Plot"];
export const activityConfig = {

  // ── Auth ─────────────────────────────────────────────────────────────────

  LOGIN: {
    icon: "🔐",
    color: "#4361EE",
    label: "Login",
    text: (meta) =>
      `Successfully signed in via ${meta?.device ?? "unknown device"}.`,
  },
 
  GOOGLE_LOGIN: {
    icon: "🔐",
    color: "#4361EE",
    label: "Google Login",
    text: (meta) =>
      `Signed in with Google on ${meta?.device ?? "Desktop"}.`,
  },

  // Microsoft OAuth login
  MICROSOFT_LOGIN: {
    icon: "🔐",
    color: "#4361EE",
    label: "Microsoft Login",
    text: (meta) =>
      `Signed in with Microsoft on ${meta?.device ?? "Desktop"}.`,
  },

  LOGOUT: {
    icon: "🚪",
    color: "#888",
    label: "Logout",
    text: () => "Signed out of your RentSmart account.",
  },

  PASSWORD_RESET: {
    icon: "🔑",
    color: "#2D6A4F",
    label: "Password Reset",
    text: (meta) =>
      `Your password was successfully reset${meta?.ip ? ` from IP ${meta.ip}` : ""}.`,
  },

 
  PROFILE_UPDATED: {
    icon: "👤",
    color: "#4361EE",
    label: "Profile Updated",
    text: (meta) =>
      `Updated your ${meta?.field ?? "profile"} information successfully.`,
  },

  EMAIL_VERIFIED: {
    icon: "✅",
    color: "#2D6A4F",
    label: "Email Verified",
    text: () =>
      "Your email address has been successfully verified and your account security has been enhanced.",
  },

  // ── Properties ────────────────────────────────────────────────────────────

  PROPERTY_CREATED: {
    icon: "🏠",
    color: "#2D6A4F",
    label: "Property Listed",
    text: (meta) =>
      `Your property "${meta?.propertyTitle ?? "Untitled Property"}" has been published and is now visible to potential buyers and tenants.`,
  },

  PROPERTY_EDITED: {
    icon: "✏️",
    color: "#C8A96E",
    label: "Property Updated",
    text: (meta) =>
      `Updated information, pricing, images, or details for "${meta?.propertyTitle ?? "a property"}".`,
  },

  PROPERTY_DELETED: {
    icon: "🗑️",
    color: "#C0392B",
    label: "Property Removed",
    text: (meta) =>
      `Removed "${meta?.propertyTitle ?? "a property"}" from active listings.`,
  },

  PROPERTY_SAVED: {
    icon: "🔖",
    color: "#4361EE",
    label: "Saved Property",
    text: (meta) =>
      `Added "${meta?.propertyTitle ?? "a property"}" to your saved properties list for future reference.`,
  },

  PROPERTY_UNSAVED: {
    icon: "💔",
    color: "#888",
    label: "Removed from Saved",
    text: (meta) =>
      `Removed "${meta?.propertyTitle ?? "a property"}" from your saved properties.`,
  },

  // ── Contact ───────────────────────────────────────────────────────────────

  CONTACT_REVEALED: {
    icon: "📞",
    color: "#7B2FBE",
    label: "Contact Unlocked",
    text: (meta) =>
      `Successfully unlocked the owner's contact details for "${meta?.propertyTitle ?? "a property"}". You can now connect directly with the property owner.`,
  },

  CONTACT_VIEWED: {
    icon: "👀",
    color: "#7B2FBE",
    label: "New Interested Buyer",
    text: (meta) =>
      `${meta?.buyerName ?? "A user"} has unlocked your contact details for "${meta?.propertyTitle ?? "a property"}". Contact Information: ${meta?.buyerEmail ?? "Email unavailable"} • ${meta?.buyerPhone ?? "Phone unavailable"}. They may contact you soon regarding this property.`,
  },

 
  MESSAGE_SENT: {
    icon: "💬",
    color: "#4361EE",
    label: "Message Sent",
    text: (meta) =>
      `Sent an inquiry message regarding "${meta?.propertyTitle ?? "a property"}".`,
  },

  
  PAYMENT_MADE: {
    icon: "💳",
    color: "#C8A96E",
    label: "Payment Initiated",
    text: (meta) =>
      `Payment of ₹${meta?.amount?.toLocaleString("en-IN") ?? "—"} initiated for "${meta?.propertyTitle ?? "a listing"}".`,
  },

  PAYMENT_COMPLETED: {
    icon: "💰",
    color: "#2D6A4F",
    label: "Payment Successful",
    text: (meta) =>
      `Payment of ₹${meta?.amount?.toLocaleString("en-IN") ?? "—"} completed successfully for "${meta?.propertyTitle ?? "a listing"}".`,
  },
 
  LISTING_PROMOTED: {
    icon: "⭐",
    color: "#C8A96E",
    label: "Featured Listing",
    text: (meta) =>
      `"${meta?.propertyTitle ?? "a listing"}" has been promoted to featured status for increased visibility.`,
  },
};
 
export const navItems = [
  { icon: "⊞", label: "Overview", id: "overview" },
  { icon: "🏠", label: "My Listings", id: "listings" },
  { icon: "❤️", label: "Saved", id: "saved" },
  { icon: "🔎", label: "Search For Rent", id: "rent", link: "/search-for-property/rent", tab: true },
  { icon: "🔎", label: "Search For Buy", id: "buy", link: "/search-for-property/sell", tab: true },
  { icon: "💳", label: "Payments", id: "payments" },
  { icon: "⚙️", label: "Settings", id: "settings" },
  { icon: "💬", label: "Messages", id: "messages" },
  { icon: "👁️", label: "Recently Viewed", id: "recent" },
];

export const AMENITY_ICONS = {
  "Lift": "🛗",
  "Air Conditioning": "❄️",
  "Security": "🔒",
  "Parking": "🅿️",
  "Swimming Pool": "🏊",
  "Garden": "🌿",
  "Gym": "🏋️",
  "Wifi": "📶",
  "Meals Included": "🍽️",
  "Laundry": "🧺",
  "Conference Room": "📊",
  "Terrace": "🏙️",
  "24/7 Security": "👮",
  "CCTV": "📷",
  "Power Backup": "🔋",
  "Generator": "⚡",
  "Clubhouse": "🏛️",
  "Children's Play Area": "🛝",
  "Housekeeping": "🧹",
  "Loading Dock": "🚚",
  "Beach Access": "🏖️",
  "BBQ Area": "🔥",
  "Cafeteria": "☕",
  "24/7 Access": "🕐",
  "Lawn": "🌱",
  "Kitchen Exhaust": "🍳",
  "Water Purifier": "💧",
  "Rooftop Lounge": "🌆",
  "Wide Roads": "🛣️",
  "Main Road Facing": "📍",
  "Corner Plot": "📐",
  "HMDA Approved": "✅",
  "BMRDA Approved": "✅",
  "Gated Community": "🚪",
};
